### ISSUE TITLE
How to include Postgresql bindings in Function deployments?

### ISSUE THREAD

**Issue by arift** [Azure/azure-functions-postgresql-extension#19]
So far running the sample projects locally results in `The binding type(s) 'postgresql' were not found in the configured extension bundle` error. Deploying them to Azure also leads to similar errors, preventing function to start. 

Any suggestions or pointers on how to get started on using this extension?

**Comment by npollock14** [comment]
Hi, this extension is still in development and an official bundle has not been created that includes this extension yet. You could run this locally if you create a custom bundle yourself but deploying to Azure may not be possible yet. 
I used this to custom bundle while developing locally: https://github.com/Azure/azure-functions-extension-bundles
Let me know if you have any further questions.

**Comment by arift** [comment]
I see, I didn't realize it was still in development. Thank you for your quick response.
